version: "3.8"
services:
  twilio_sms_sender_api:
    image: elleined/twilio-sms-sender-api:latest
    container_name: twilio_sms_sender_api
    env_file:
      - .env
    ports:
      - "8070:8070"
    networks:
      - twilio_sms_sender_api_network
networks:
  twilio_sms_sender_api_network:
    name: twilio_sms_sender_api_network
    external: false
    ipam:
      driver: default